services:
  # s3:
  #   image: minio/minio:latest
  #   container_name: signer-s3
  #   ports:
  #     - "${S3_PORT:-9000}:9000"
  #   environment:
  #     MINIO_ROOT_USER: minioadmin
  #     MINIO_ROOT_PASSWORD: minioadmin
  #   command: server /data
  #   volumes:
  #     - s3_data:/data
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
  #     interval: 30s
  #     timeout: 20s
  #     retries: 3
  #   entrypoint: >
  #     /bin/sh -c "
  #     minio server /data && \
  #     (while ! curl -s http://localhost:9000/minio/health/live; do sleep 1; done) && \
  #     mc alias set myminio http://localhost:9000 minioadmin minioadmin && \
  #     mc mb myminio/signer-bucket
  #     "

  redis:
    image: redis:latest
    container_name: signer-redis
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data

  asynqmon:
    image: asynqmon
    container_name: signer-asynqmon
    ports:
      - "${ASYNQMON_PORT:-8020}:8080"
    environment:
      REDIS_URL: redis://signer-redis:6379/0

volumes:
  # s3_data:
  redis_data:
